# Generated by Django 3.2.5 on 2021-07-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_manage_an_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='made_an_order',
            field=models.BooleanField(default=False),
        ),
    ]
